% Krzysztof Madaliński WMT23AP1S1 30.04.2026
% kod generujący filtr II rzędu z wykorzystaniem aproksymacji Butterwortha

function Hd = filtr2
%FILTRY Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 27-Apr-2026 23:31:41

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 48;  % Sampling Frequency

N  = 2;    % Order
Fc = 4.8;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
%% Pobranie parametrów tranmitancji Filtra
[num, den] = tf(Hd);
num = round(num, 3);
den = round(den, 3);
H = tf(num, den, 1/Fs);
%wyświetlenie transmitancji
display(H); 
%% Sprawdzenie stabilności
p = roots(den);
display(round(abs(p),2));


% [EOF]
